# Generated by Django 3.2.18 on 2023-05-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20230527_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order_item',
            new_name='orderitem',
        ),
    ]
