# Generated by Django 3.2.18 on 2023-06-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20230607_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='storetype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.storetype'),
        ),
    ]
