# Generated by Django 3.2.18 on 2023-06-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='users/buyers/images/profiles/'),
        ),
    ]
